# Generated by Django 3.0 on 2019-12-08 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191208_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='Random', max_length=30),
        ),
    ]
