# Generated by Django 3.0 on 2019-12-10 07:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20191209_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(default='Content'),
            preserve_default=False,
        ),
    ]
