# Generated by Django 3.0 on 2019-12-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20191210_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment_count',
        ),
    ]
